# Generated by Django 5.1.1 on 2024-11-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_blogpost_alter_item_last_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('p', 'Positive'), ('n', 'Negative')], default='p', max_length=100),
        ),
    ]
